spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak-service:8888/auth/realms/master

app:
  services:
    adidasservice:
      baseurl: https://www.adidas.co.uk
    reviewservice:
      baseurl: http://review-service:8042


