spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/auth/realms/master


app:
  services:
    adidasservice:
      baseurl: https://www.adidas.com
    reviewservice:
      baseurl: http://localhost:8042



logging:
  level:
    org:
      springframework:
        web:
          reactive:
            function:
              client:
                ExchangeFunctions: TRACE