spring:
  data:
    mongodb:
      database: product_service
      port: 2078
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak-service:8888/auth/realms/master


