spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8888/auth/realms/master/protocol/openid-connect/token
            authorization-uri: http://localhost:8888/auth/realms/master/protocol/openid-connect/auth
            userinfo-uri: http://localhost:8888/auth/realms/master/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          notion-client:
            provider: keycloak
            client-id: notion-client
            client-secret: d88acb83-4625-4ba1-8d9c-f05c66310d3d
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: product-service
          uri: http://127.0.0.1:8040
          predicates:
            - Path=/v1/products/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: review-service
          uri: http://127.0.0.1:8042
          predicates:
            - Path=/v1/reviews/**